# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', 'fill_child_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='phone',
            new_name='phones',
        ),
        migrations.AlterField(
            model_name='punchblock',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.PunchBlockType', verbose_name='тип'),
        ),
    ]
