# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_auto_20170706_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosspoint',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='journal.CrossPoint', verbose_name='откуда приходит'),
        ),
        migrations.AddField(
            model_name='historicalcrosspoint',
            name='source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='journal.HistoricalCrossPoint'),
        ),
        migrations.AddField(
            model_name='historicalpbxport',
            name='source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='journal.CrossPoint'),
        ),
        migrations.AddField(
            model_name='historicalphone',
            name='source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='journal.CrossPoint'),
        ),
        migrations.AddField(
            model_name='historicalpunchblock',
            name='source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='journal.CrossPoint'),
        ),
    ]
