# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchBlock',
            fields=[
                ('crosspoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journal.CrossPoint')),
                ('number', models.SmallIntegerField(verbose_name='номер')),
                ('type', models.CharField(choices=[('city', 'Гром-полоса'), ('extension', 'Распределение'), ('trunk', 'Магистраль')], default='trunk', max_length=9, verbose_name='тип')),
                ('is_station', models.BooleanField(verbose_name='станционная (-ое)')),
            ],
            options={
                'verbose_name': 'плинт',
                'verbose_name_plural': 'плинты',
            },
            bases=('journal.crosspoint',),
        ),
        migrations.RemoveField(
            model_name='extension',
            name='crosspoint_ptr',
        ),
        migrations.RemoveField(
            model_name='trunk',
            name='crosspoint_ptr',
        ),
        migrations.DeleteModel(
            name='Extension',
        ),
        migrations.DeleteModel(
            name='Trunk',
        ),
    ]
