# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 21:55
from __future__ import unicode_literals

from django.db import migrations


def migrate_destination_to_source(apps, schema_editor):
    CrossPoint = apps.get_model('journal', 'CrossPoint')

    for cp in CrossPoint.objects.all():
        cp.source = cp.destination
        cp.save_without_historical_record()


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20170709_0049'),
    ]

    operations = [
        migrations.RunPython(migrate_destination_to_source),
    ]
