# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20170504_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='PBXRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journal.Room', verbose_name='помещение')),
            ],
            options={
                'verbose_name_plural': 'станционные помещения',
                'verbose_name': 'станционное помещение',
            },
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='journal.Phone', verbose_name='телефоны'),
        ),
    ]
