# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20170510_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.ManyToManyField(related_name='subscribers', to='journal.Phone', verbose_name='телефоны'),
        ),
    ]
