# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20170709_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosspoint',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='journal.CrossPoint', verbose_name='откуда приходит'),
        ),
    ]
