# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20170709_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crosspoint',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='historicalcrosspoint',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='historicalpbxport',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='historicalphone',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='historicalpunchblock',
            name='destination',
        ),
    ]
