# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 17:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0006_historicalbuilding_historicalcabinet_historicalcrosspoint_historicallocation_historicalpbxport_histo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPBX',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('asterisk', 'Asterisk'), ('avaya', 'Avaya'), ('m-200', 'М-200'), ('multicom', 'Мультиком'), ('panasonic', 'Panasonic')], max_length=10, verbose_name='производитель')),
                ('model', models.CharField(max_length=40, verbose_name='модель')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'history_date',
                'verbose_name': 'historical АТС',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
    ]
