# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 18:30
from __future__ import unicode_literals

from django.db import migrations


def populate_char_number(apps, schema_editor):
    PunchBlock = apps.get_model('journal', 'PunchBlock')

    for pb in PunchBlock.objects.all():
        pb.char_number = '{:04d}'.format(pb.number)
        pb.save()


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20170709_2128'),
    ]

    operations = [
        migrations.RunPython(populate_char_number),
    ]
