# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_historicalpbx'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpbxport',
            name='json_path',
            field=models.TextField(blank=True, editable=False, verbose_name='маршрут в формате JSON'),
        ),
        migrations.AddField(
            model_name='pbxport',
            name='json_path',
            field=models.TextField(blank=True, editable=False, verbose_name='маршрут в формате JSON'),
        ),
    ]
