# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_auto_20170709_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpunchblock',
            name='number',
        ),
        migrations.RemoveField(
            model_name='punchblock',
            name='number',
        ),
    ]
