# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20170709_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpunchblock',
            old_name='char_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='punchblock',
            old_name='char_number',
            new_name='number',
        ),
    ]
