# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_historicalpunchblocktype_punchblocktype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpunchblocktype',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical тип плинта'},
        ),
        migrations.AlterModelOptions(
            name='punchblocktype',
            options={'verbose_name': 'тип плинта', 'verbose_name_plural': 'типы плинтов'},
        ),
    ]
