# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20170630_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpunchblock',
            name='type_tmp',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='journal.PunchBlockType'),
        ),
        migrations.AddField(
            model_name='punchblock',
            name='type_tmp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.PunchBlockType', verbose_name='тип'),
            preserve_default=False,
        ),
    ]
