# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 08:27
from __future__ import unicode_literals

from django.db import migrations


def fill_pbx_location(apps, schema_editor):
    PBX = apps.get_model('journal', 'PBX')
    Location = apps.get_model('journal', 'Location')

    try:
        fallback_location = Location.objects.filter(room__pbxroom__isnull=False)[0]
    except IndexError:
        pass

    for pbx in PBX.objects.all():
        ports = pbx.pbxport_set.all()

        if len(ports) > 0:
            pbx.location = ports[0].location
        else:
            pbx.location = fallback_location

        pbx.save()


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20170710_1127'),
    ]

    operations = [
        migrations.RunPython(fill_pbx_location),
    ]
