# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_auto_20170621_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpunchblock',
            old_name='type_tmp',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='punchblock',
            old_name='type_tmp',
            new_name='type',
        ),
    ]
