# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_auto_20170710_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='number',
            field=models.CharField(max_length=5, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='historicalbuilding',
            name='number',
            field=models.CharField(max_length=5, verbose_name='номер'),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together=set([('number', 'letter')]),
        ),
    ]
