# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_auto_20170621_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pbxport',
            options={'ordering': ['subscriber_number'], 'verbose_name': 'порт АТС', 'verbose_name_plural': 'порты АТС'},
        ),
        migrations.AddField(
            model_name='crosspoint',
            name='child_class',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='дочерний класс'),
        ),
        migrations.AddField(
            model_name='historicalcrosspoint',
            name='child_class',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='дочерний класс'),
        ),
        migrations.AddField(
            model_name='historicalpbxport',
            name='child_class',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='дочерний класс'),
        ),
        migrations.AddField(
            model_name='historicalphone',
            name='child_class',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='дочерний класс'),
        ),
        migrations.AddField(
            model_name='historicalpunchblock',
            name='child_class',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='дочерний класс'),
        ),
    ]
