# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_auto_20170711_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpbxport',
            name='subscriber_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='абонентский номер'),
        ),
        migrations.AlterField(
            model_name='pbxport',
            name='subscriber_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='абонентский номер'),
        ),
    ]
