# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_auto_20170713_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosspoint',
            name='main_source',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='journal.CrossPoint', verbose_name='порт-источник'),
        ),
        migrations.AddField(
            model_name='historicalcrosspoint',
            name='main_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='journal.HistoricalCrossPoint'),
        ),
        migrations.AddField(
            model_name='historicalpbxport',
            name='main_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='journal.CrossPoint'),
        ),
        migrations.AddField(
            model_name='historicalphone',
            name='main_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='journal.CrossPoint'),
        ),
        migrations.AddField(
            model_name='historicalpunchblock',
            name='main_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='journal.CrossPoint'),
        ),
    ]
