# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_auto_20170714_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosspoint',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='уровень'),
        ),
        migrations.AddField(
            model_name='historicalcrosspoint',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='уровень'),
        ),
        migrations.AddField(
            model_name='historicalpbxport',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='уровень'),
        ),
        migrations.AddField(
            model_name='historicalphone',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='уровень'),
        ),
        migrations.AddField(
            model_name='historicalpunchblock',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='уровень'),
        ),
    ]
