# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 20:31
from __future__ import unicode_literals

from django.db import migrations


def fill_contenttypes(apps, schema_editor):
    PBXPort = apps.get_model('journal', 'PBXPort')
    PunchBlock = apps.get_model('journal', 'PunchBlock')
    Phone = apps.get_model('journal', 'Phone')

    ContentType = apps.get_model('contenttypes', 'ContentType')

    new_pbxport_ct = ContentType.objects.get_for_model(PBXPort)
    PBXPort.objects.all().update(polymorphic_ctype=new_pbxport_ct)

    new_pb_ct = ContentType.objects.get_for_model(PunchBlock)
    PunchBlock.objects.all().update(polymorphic_ctype=new_pb_ct)

    new_phone_ct = ContentType.objects.get_for_model(Phone)
    Phone.objects.all().update(polymorphic_ctype=new_phone_ct)


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0020_auto_20170718_2328'),
    ]

    operations = [
        migrations.RunPython(
            fill_contenttypes,
            reverse_code=lambda *args: None,
        ),
    ]
