# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0021_auto_20170718_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpunchblock',
            name='number',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='punchblock',
            name='number',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='номер'),
        ),
    ]
