# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('journal', '0022_auto_20170721_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionBox',
            fields=[
                ('crosspoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journal.CrossPoint')),
                ('box_number', models.CharField(blank=True, max_length=5, verbose_name='номер коробки')),
                ('pair_number', models.PositiveSmallIntegerField(verbose_name='номер плинта')),
            ],
            options={
                'verbose_name_plural': 'КРТ',
                'verbose_name': 'КРТ',
            },
            bases=('journal.crosspoint',),
        ),
        migrations.CreateModel(
            name='HistoricalExtensionBox',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='уровень')),
                ('child_class', models.CharField(blank=True, editable=False, max_length=100, verbose_name='дочерний класс')),
                ('box_number', models.CharField(blank=True, max_length=5, verbose_name='номер коробки')),
                ('pair_number', models.PositiveSmallIntegerField(verbose_name='номер плинта')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('crosspoint_ptr', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='journal.CrossPoint')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='journal.Location')),
                ('main_source', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='journal.CrossPoint')),
                ('polymorphic_ctype', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.ContentType')),
                ('source', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='journal.CrossPoint')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical КРТ',
                'get_latest_by': 'history_date',
            },
        ),
    ]
