# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0023_extensionbox_historicalextensionbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionbox',
            name='box_number',
            field=models.CharField(max_length=5, verbose_name='номер коробки'),
        ),
        migrations.AlterField(
            model_name='historicalextensionbox',
            name='box_number',
            field=models.CharField(max_length=5, verbose_name='номер коробки'),
        ),
    ]
