# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0024_auto_20170723_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalphone',
            name='jack',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='номер розетки'),
        ),
        migrations.AddField(
            model_name='phone',
            name='jack',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='номер розетки'),
        ),
    ]
