# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 13:58
from __future__ import unicode_literals

from django.db import migrations, models


def create_base_types(apps, schema_editor):
    PBXPortType = apps.get_model('journal', 'PBXPortType')

    pbx_port_types = (
        'SIP',
        'Аналоговый',
        'E1',
    )

    for port_type in pbx_port_types:
        PBXPortType.objects.create(name=port_type)


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0026_auto_20170925_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='PBXPortType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name_plural': 'Типы портов АТС',
                'verbose_name': 'Тип порта АТС',
            },
        ),
        migrations.RunPython(create_base_types, reverse_code=lambda x, y: None)
    ]
