# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 10:02
from __future__ import unicode_literals

from django.db import migrations


def link_pbx_port_types(apps, schema_editor):
    PBXPort = apps.get_model('journal', 'PBXPort')
    PBXPortType = apps.get_model('journal', 'PBXPortType')

    pbx_port_types = (
        ('sip', 'SIP'),
        ('analog', 'Аналоговый'),
        ('pri', 'E1'),
    )

    for pbx_port_type in pbx_port_types:
        port, created = PBXPortType.objects.get_or_create(name=pbx_port_type[1])

        PBXPort.objects.filter(type=pbx_port_type[0]).update(type_tmp=port)


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0028_auto_20171206_1301'),
    ]

    operations = [
        migrations.RunPython(link_pbx_port_types, reverse_code=lambda x, y: None),
    ]
