# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0029_transfer_pbx_port_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpbxport',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pbxport',
            name='type',
        ),
        migrations.RenameField(
            model_name='historicalpbxport',
            old_name='type_tmp',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='pbxport',
            old_name='type_tmp',
            new_name='type',
        ),
    ]
