# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0030_auto_20171206_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmptyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='extensionbox',
            name='type',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.EmptyType'),
        ),
        migrations.AddField(
            model_name='historicalextensionbox',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='journal.EmptyType'),
        ),
    ]
